name: yamly

on:
  push:
    branches: 
      - "main"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.21 ]
    name: Tests with Go ${{ matrix.go-version }} 
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./... \;

    - name: Build engines
      run: find ./engines -type f -name go.mod -execdir go build -v ./...

    - name: Test
      run: go test -race -v ./...

    - name: Test engines
      run: find ./engines -type f -name go.mod -execdir go test -race -v ./...

    - name: Test integration
      run: cd ./test && go test -race -v ./...
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module: [".", "./engines/yayamls", "./engines/goyaml", "./test"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
          working-directory: ${{ matrix.module }}
          args: --timeout=5m --config=./.golangci.yaml -v
        
  
